name: Flags

on:
  push:
  pull_request:

jobs:
    test:
      name: Compile and Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Build and Test
          run: |
            export MAVEN_OPTS="-XX:+PrintFlagsFinal" 
            xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage
            unset MAVEN_OPTS