name: Java CI with Maven and MAVEN_OPTS Matrix

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_version:
          - '17'
          # - '18'
          # - '19'
          - '20'
          # - '21'
          # - '22'
          - '23'
          # - '24' - don't exist yet
        maven_opts:
          - "-XX:-UseG1GC -XX:+UseZGC" # Change GC (Garbage Collector)
          - "-XX:MaxGCPauseMillis=2000" # GC with more pause time
          - "-Xmx256m -Xms256m" # Compilation with less memory

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jvm_version }}
    - name: Build and Test with Maven
      timeout-minutes: 15
      run: |
        export MAVEN_OPTS="${{ matrix.maven_opts }}" 
        ./mvnw -B verify
        unset MAVEN_OPTS
        
    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Fail if coverage has not improved.
      run: |
        coverage=$COVERAGE
        threshold=24.46
        if (( $(echo "$coverage <= $threshold" | bc -l) )); then
          echo "Coverage ($coverage%) is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi